version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" 
      - "1025:1025"

volumes:
  mongo-data:
