# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: card.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CardPost(betterproto.Message):
    front: str = betterproto.string_field(1)
    back: str = betterproto.string_field(2)


@dataclass
class CardGet(betterproto.Message):
    message: str = betterproto.string_field(1)
